# Generated by Django 5.2.6 on 2025-09-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='incidente',
            name='latitud',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='incidente',
            name='longitud',
            field=models.FloatField(default=None),
        ),
    ]
