# Generated by Django 5.2.6 on 2025-09-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0003_remove_incidente_ubicacion_incidente_latitud_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidente',
            name='titulo',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
