# Generated by Django 5.2.7 on 2025-11-10 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0004_incidente_titulo'),
        ('recursos', '0006_remove_recurso_usuario_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_recurso', to='recursos.recurso'),
        ),
    ]
