# Generated by Django 5.2.7 on 2025-11-11 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentes', '0005_alter_asignacion_recurso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidente',
            name='tipo',
        ),
        migrations.DeleteModel(
            name='TipoIncidente',
        ),
    ]
