# Generated by Django 5.2.7 on 2025-11-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='ubicacion',
        ),
        migrations.AddField(
            model_name='recurso',
            name='latitud',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='recurso',
            name='longitud',
            field=models.FloatField(default=None),
        ),
    ]
