# Generated by Django 5.2.6 on 2025-11-04 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0002_remove_recurso_ubicacion_recurso_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='recurso',
            name='longitud',
        ),
        migrations.AddField(
            model_name='institucion',
            name='latitud',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='institucion',
            name='longitud',
            field=models.FloatField(default=None),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
