# Generated by Django 5.2.6 on 2025-11-04 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0003_remove_recurso_latitud_remove_recurso_longitud_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recurso',
            old_name='tipo',
            new_name='institucion_base',
        ),
    ]
