# Generated by Django 5.2.7 on 2025-11-09 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0004_rename_tipo_recurso_institucion_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recursos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='latitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='longitud',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
