# Generated by Django 5.2.7 on 2025-11-09 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0005_recurso_usuario_asignado_alter_institucion_latitud_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recurso',
            name='usuario_asignado',
        ),
    ]
