# Generated by Django 5.2.7 on 2025-11-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0006_remove_recurso_usuario_asignado'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
