# Generated by Django 5.2.7 on 2025-11-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0007_institucion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institucion',
            name='tipo',
        ),
    ]
