# Generated by Django 5.2.7 on 2025-11-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recursos', '0008_remove_institucion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurso',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='estado',
            field=models.CharField(default='DISPONIBLE', max_length=20),
        ),
    ]
